# Generated by Django 5.2.8 on 2025-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('original_language', models.CharField(default='en', max_length=10)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('translated_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notes_note_created_cf5022_idx'), models.Index(fields=['original_language'], name='notes_note_origina_6d70bd_idx')],
            },
        ),
    ]
